# Generated by Django 4.0.3 on 2022-07-23 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Oppkg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('nfs', models.ManyToManyField(to='books.networkfunction')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.operator')),
            ],
            options={
                'verbose_name': 'SW Package',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SwPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('num_4gm', models.IntegerField()),
                ('num_5gm', models.IntegerField()),
                ('oppkg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.oppkg')),
            ],
            options={
                'verbose_name': '가입자수와 Tput',
                'ordering': ['oppkg', 'year'],
            },
        ),
        migrations.AddField(
            model_name='oppkg',
            name='sw_pkg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.swpackage'),
        ),
    ]
