# Generated by Django 4.0.3 on 2022-07-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_networkfunction_operator_oppkg_swpackage_subscriber_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NetworkFunction',
            new_name='Nf',
        ),
    ]
