# Generated by Django 4.0.3 on 2022-07-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_oppkg_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='num_5gf',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
