# Generated by Django 4.0.3 on 2022-07-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_subscriber_num_5gf'),
    ]

    operations = [
        migrations.AddField(
            model_name='oppkg',
            name='sess_5gm',
            field=models.IntegerField(default=0),
        ),
    ]
