# Generated by Django 4.0.3 on 2022-08-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_oppkg_sess_5gm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oppkg',
            options={'ordering': ['created_at'], 'verbose_name': 'Operators and Packages'},
        ),
        migrations.AlterField(
            model_name='oppkg',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
